### ISSUE TITLE
Create sample synchronous pipeline job

### ISSUE THREAD

**Issue by madendorff** [Anaplan-Initiatives/mycroft#3]
Show how to chain together workers to do something more interesting
e.g. read file, transform, write

Implement this a Pipeline. Inherit from BaseWorker.
A pipeline is one way of composing a job from multiple workers.
In a pipeline, first worker is a data source that will be processed with its read() method.
Subsequent workers run sequentially - accepting the output of the previous worker as input to the execute() method and mutating it as output.

**Comment by Anaplan-Initiatives** [comment]
added Pipeline class with example of how to use it
